//
//  VKAuthScreenAssembly.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "VKAuthScreenAssembly.h"
#import "VKAuthScreenViewController.h"
#import "VKAuthScreenPresenter.h"
#import "VKAuthScreenProtocols.h"
#import "VKAuthScreenRouter.h"

@interface VKAuthScreenAssembly ()

@end

@implementation VKAuthScreenAssembly

+ (UIViewController *)createModule {
    VKAuthScreenViewController *view = [[VKAuthScreenViewController alloc] init];
    VKAuthScreenRouter *router = [[VKAuthScreenRouter alloc] init];
    VKAuthScreenPresenter *presenter = [[VKAuthScreenPresenter alloc] initWithView:view router:router];
    view.presenter = presenter;
    router.viewController = view;
    return view;
}

@end
