//
//  AddMealProtocols.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 19/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

//Router implement navigateTo func
@protocol AddMealWireframeInterface <NSObject>

//example
@required - (void)navigateToDismiss;

@end

@protocol AddMealView <NSObject>

@end

@protocol AddMealPresenterInterface <NSObject>

- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidAppear;
- (void)viewWillDissappear;
- (void)viewDidDissappear;

- (void)didSelectFinishButton;
- (void)didSelectDismissButton;

@end


NS_ASSUME_NONNULL_END
