//
//  AddMealAssembly.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 19/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <UIKit/UIKit.h>

@interface AddMealAssembly: NSObject

+ (UIViewController *)createModuleWithIndex:(NSUInteger)index;

@end
