//
//  TabBarAssembly.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 21/04/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <UIKit/UIKit.h>

@interface TabBarAssembly: NSObject

+ (UIViewController *)createModule;

@end
