//
//  MealTimePresenter.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "MealTimeProtocols.h"

@interface MealTimePresenter: NSObject<MealTimePresenterInterface>
@property (nonatomic, weak) NSObject<MealTimeView> *view;
- (instancetype)initWithView:(NSObject<MealTimeView>*)view
                      router:(NSObject<MealTimeWireframeInterface>*)router;
@end


