//
//  TabBarViewController.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 21/04/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "TabBarViewController.h"
#import "MainMenuAssembly.h"
#import <UIKit/UIKit.h>

@interface TabBarViewController () <TabBarView>

@end

@implementation TabBarViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    [self configureUI];
    [self configureInitialVCs];
    [self.presenter viewDidLoad];
}

- (void)configureUI {
    //configure UI
}

- (void)configureInitialVCs
{
    UIViewController *mainMenu = [MainMenuAssembly createModule];
    UINavigationController *nav1 = [[UINavigationController alloc] initWithRootViewController:mainMenu];
    nav1.title = @"Меню";
    
    [self setViewControllers:@[nav1] animated:YES];
    self.tabBar.items[0].image = [[UIImage imageNamed: @"Menu"] imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
    self.tabBar.items[0].selectedImage = [[UIImage imageNamed: @"Menu"] imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
}

@end
