//
//  MealTimeViewController.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <UIKit/UIKit.h>
#import "MealTimeProtocols.h"

NS_ASSUME_NONNULL_BEGIN

@interface MealTimeViewController : UIViewController<MealTimeView>

@property (nonatomic, strong) NSObject<MealTimePresenterInterface>* presenter;

@end

NS_ASSUME_NONNULL_END
