//
//  MainMenuAssembly.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 21/04/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "MainMenuAssembly.h"
#import "MainMenuViewController.h"
#import "MainMenuPresenter.h"
#import "MainMenuProtocols.h"
#import "MainMenuRouter.h"

@interface MainMenuAssembly ()

@end

@implementation MainMenuAssembly

+ (UIViewController *)createModule {
    MainMenuViewController *view = [[MainMenuViewController alloc] init];
    MainMenuRouter *router = [[MainMenuRouter alloc] init];
    MainMenuPresenter *presenter = [[MainMenuPresenter alloc] initWithView:view router:router];
    view.presenter = presenter;
    router.viewController = view;
    return view;
}

@end
