//
//  ProfileAssembly.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <UIKit/UIKit.h>

@interface ProfileAssembly: NSObject

+ (UIViewController *)createModule;

@end
