//
//  VKAuthScreenRouter.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "VKAuthScreenProtocols.h"

NS_ASSUME_NONNULL_BEGIN

@interface VKAuthScreenRouter : NSObject<VKAuthScreenWireframeInterface>

@property (weak, nonatomic) UIViewController *viewController;

@end

NS_ASSUME_NONNULL_END