//
//  AddMealPresenter.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 19/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "AddMealProtocols.h"

@interface AddMealPresenter: NSObject<AddMealPresenterInterface>
@property (nonatomic, weak) NSObject<AddMealView> *view;
- (instancetype)initWithView:(NSObject<AddMealView>*)view router:(NSObject<AddMealWireframeInterface>*)router index:(NSUInteger)index;

@end


