//
//  MealTimeAssembly.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "MealTimeAssembly.h"
#import "MealTimeViewController.h"
#import "MealTimePresenter.h"
#import "MealTimeProtocols.h"
#import "MealTimeRouter.h"

@interface MealTimeAssembly ()

@end

@implementation MealTimeAssembly

+ (UIViewController *)createModule {
    MealTimeViewController *view = [[MealTimeViewController alloc] init];
    MealTimeRouter *router = [[MealTimeRouter alloc] init];
    MealTimePresenter *presenter = [[MealTimePresenter alloc] initWithView:view router:router];
    view.presenter = presenter;
    router.viewController = view;
    return view;
}

@end
