//
//  MealTimeProtocols.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

//Router implement navigateTo func
@protocol MealTimeWireframeInterface <NSObject>

//example
@required - (void)navigateToDismiss;

@end

@protocol MealTimeView <NSObject>

@end

@protocol MealTimePresenterInterface <NSObject>

- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidAppear;
- (void)viewWillDissappear;
- (void)viewDidDissappear;

@end


NS_ASSUME_NONNULL_END
