//
//  AddMealProtocols.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 19/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import "AddMealDataMediator.h"


NS_ASSUME_NONNULL_BEGIN

//Router implement navigateTo func
@protocol AddMealWireframeInterface <NSObject>

//example
@required
- (void)navigateToDismiss;
- (void)navigateToPop;

@end

@protocol AddMealView <NSObject>

- (void)displayReadyToSave;
- (void)displayNotReadyToSave;
- (void)displayData:(NSArray <AddMealDataMediator *>*)data;

@end

@protocol AddMealPresenterInterface <NSObject>

- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidAppear;
- (void)viewWillDissappear;
- (void)viewDidDissappear;

- (void)didSelectFinishButton;
- (void)didSelectDismissButton;
- (void)didEnterTextAtIndexPath:(NSIndexPath *)indexPath text:(NSString *)text;

@end


NS_ASSUME_NONNULL_END
