//
//  AddMealViewController.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 19/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "AddMealViewController.h"
#import <UIKit/UIKit.h>
#import "UIView+Constraints.h"


@interface AddMealViewController () <AddMealView>

@property (strong, nonatomic) UITableView *tableView;

@end


@implementation AddMealViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    [self configureUI];
    [self.presenter viewDidLoad];
}

- (void)configureUI
{
    UIButton *button = [UIButton new];
    [self.view addSubview:button];
    self.view.backgroundColor = UIColor.whiteColor;
    [button fillSuperview];
    [button setTitle:@"ДОБАВИТЬ ГРУДКУ" forState:UIControlStateNormal];
    [button setTitleColor:UIColor.blueColor forState:UIControlStateNormal];
    button.titleLabel.font = [UIFont systemFontOfSize:30];
    button.titleLabel.numberOfLines = 0;
    [button addTarget:self action:@selector(didSelectAddChickenButton) forControlEvents:UIControlEventTouchUpInside];
}

- (void)didSelectAddChickenButton
{
    [self.presenter didSelectFinishButton];
}

- (void)didSelectDismissButton
{
    [self.presenter didSelectDismissButton];
}

- (void)dealloc
{
    NSLog(@"DEALLOC");
}
@end
