//
//  AddMealRouter.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 19/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "AddMealRouter.h"
#import "AddMealProtocols.h"


@implementation AddMealRouter

- (void)navigateToDismiss
{ 
    [self.viewController dismissViewControllerAnimated:true completion:nil];
}

- (void)navigateTo:(UIViewController *)viewController
{
    if([viewController isKindOfClass:[UINavigationController class]]){
        [self.viewController presentViewController:viewController animated:true completion:nil];
    } else if ([viewController isKindOfClass:[UIViewController class]]) {
        if (self.viewController.navigationController){
            [self.viewController.navigationController pushViewController:viewController animated:true];
        } else {
            [self.viewController presentViewController:viewController animated:true completion:nil];
        }
    }
}

@end
