//
//  AddMealAssembly.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 19/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "AddMealAssembly.h"
#import "AddMealViewController.h"
#import "AddMealPresenter.h"
#import "AddMealProtocols.h"
#import "AddMealRouter.h"


@interface AddMealAssembly ()

@end


@implementation AddMealAssembly

+ (UIViewController *)createModuleWithIndex:(NSUInteger)index
{
    AddMealViewController *view = [[AddMealViewController alloc] init];
    AddMealRouter *router = [[AddMealRouter alloc] init];
    AddMealPresenter *presenter = [[AddMealPresenter alloc] initWithView:view router:router index:index];
    view.presenter = presenter;
    router.viewController = view;
    return view;
}

@end
