//
//  AddMealPresenter.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 19/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "AddMealPresenter.h"
#import "AddMealProtocols.h"
#import "AppNotes.h"
#import "MealTimeDTO.h"


@interface AddMealPresenter () <AddMealPresenterInterface>
@property (strong, nonatomic) NSObject<AddMealWireframeInterface>* router;
@property (assign, nonatomic) NSUInteger index;
@end


@implementation AddMealPresenter

- (instancetype)initWithView:(NSObject<AddMealView>*)view router:(NSObject<AddMealWireframeInterface>*)router index:(NSUInteger)index
{
    self = [super init];
    if (self) {
        _view = view;
        _router = router;
        _index = index;
    }
    return self;
}

- (void)viewDidAppear
{
    //Default implementation
}

- (void)viewDidDissappear
{
    //Default implementation
}

- (void)viewDidLoad
{
}

- (void)viewWillAppear
{
    //Default implementation
}

- (void)viewWillDissappear
{
    //Default implementation
}

- (void)didSelectFinishButton
{
    MealDTO *meal = [MealDTO new];
    meal.name = @"Грудка";
    meal.fat = 20;
    meal.carbonhydrate = 20;
    meal.protein = 20;
    meal.weight = 230;
    meal.kkal = 330;
    if ([self allFieldIsValid]) //validate fields
    {
        [[NSNotificationCenter defaultCenter] postNotificationName:appNoteMealDidAdded object:nil userInfo:@{@"meal": meal, @"index":@(self.index)}];
//        [self.router navigateToDismiss];
    }
}

- (BOOL)allFieldIsValid
{
    return true; //validate
}

- (void)didSelectDismissButton
{
    [self.router navigateToDismiss];
}

@end
