//
//  MainMenuViewController.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 21/04/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <UIKit/UIKit.h>
#import "MainMenuProtocols.h"

NS_ASSUME_NONNULL_BEGIN

@interface MainMenuViewController : UIViewController<MainMenuView>

@property (nonatomic, strong) NSObject<MainMenuPresenterInterface>* presenter;

@end

NS_ASSUME_NONNULL_END
