//
//  MainMenuPresenter.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 21/04/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "MainMenuProtocols.h"

@interface MainMenuPresenter: NSObject<MainMenuPresenterInterface>
@property (nonatomic, weak) NSObject<MainMenuView> *view;
- (instancetype)initWithView:(NSObject<MainMenuView>*)view
                      router:(NSObject<MainMenuWireframeInterface>*)router;
@end


