//
//  MealTimeRouter.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "MealTimeRouter.h"
#import "MealTimeProtocols.h"
#import "AddMealAssembly.h"


@implementation MealTimeRouter

- (void)navigateToDismiss
{
    [self.viewController dismissViewControllerAnimated:true completion:nil];
}

- (void)navigateToAddMealWithIndex:(NSUInteger)index
{
    UIViewController *addMeal = [AddMealAssembly createModuleWithIndex:index];
    [self navigateTo:addMeal];
}

- (void)navigateTo:(UIViewController *)viewController
{
    if([viewController isKindOfClass:[UINavigationController class]]){
        [self.viewController presentViewController:viewController animated:true completion:nil];
    } else if ([viewController isKindOfClass:[UIViewController class]]) {
        if (self.viewController.navigationController){
            [self.viewController.navigationController pushViewController:viewController animated:true];
        } else {
            [self.viewController presentViewController:viewController animated:true completion:nil];
        }
    }
}

@end
