//
//  MealTimeProtocols.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import "MealTimeDataMediator.h"


NS_ASSUME_NONNULL_BEGIN

//Router implement navigateTo func
@protocol MealTimeWireframeInterface <NSObject>

//example
@required - (void)navigateToDismiss;
@required - (void)navigateToAddMealWithIndex:(NSUInteger)index;

@end

@protocol MealTimeView <NSObject>

- (void)displayMeals:(NSArray <MealTimeDataMediator *>*)meals;

@end

@protocol MealTimePresenterInterface <NSObject>

- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidAppear;
- (void)viewWillDissappear;
- (void)viewDidDissappear;

- (void)didSelectMealHeaderWithIndex:(NSUInteger)index;
- (void)didSelectMealFooterWithIndex:(NSUInteger)index;

@end


NS_ASSUME_NONNULL_END
