//
//  ProfileViewController.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "ProfileViewController.h"
#import <UIKit/UIKit.h>

@interface ProfileViewController () <ProfileView>

@end

@implementation ProfileViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    [self configureUI];
    [self.presenter viewDidLoad];
}

- (void)configureUI {
    //configure UI
}

@end
