//
//  ProfileAssembly.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "ProfileAssembly.h"
#import "ProfileViewController.h"
#import "ProfilePresenter.h"
#import "ProfileProtocols.h"
#import "ProfileRouter.h"

@interface ProfileAssembly ()

@end

@implementation ProfileAssembly

+ (UIViewController *)createModule {
    ProfileViewController *view = [[ProfileViewController alloc] init];
    ProfileRouter *router = [[ProfileRouter alloc] init];
    ProfilePresenter *presenter = [[ProfilePresenter alloc] initWithView:view router:router];
    view.presenter = presenter;
    router.viewController = view;
    return view;
}

@end
