//
//  ProfilePresenter.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "ProfilePresenter.h"
#import "ProfileProtocols.h"

@interface ProfilePresenter () <ProfilePresenterInterface>
@property (strong, nonatomic) NSObject<ProfileWireframeInterface>* router;
@end

@implementation ProfilePresenter

- (instancetype)initWithView:(NSObject<ProfileView>*)view router:(NSObject<ProfileWireframeInterface>*)router {
    self = [super init];
    if (self) {
        self.view = view;
        self.router = router;
    }
    return self;
}

- (void)viewDidAppear {
    //Default implementation
}

- (void)viewDidDissappear {
    //Default implementation
}

- (void)viewDidLoad {
    //Default implementation
}

- (void)viewWillAppear {
    //Default implementation
}

- (void)viewWillDissappear {
    //Default implementation
}

@end
