//
//  TabBarRouter.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 21/04/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "TabBarRouter.h"
#import "TabBarProtocols.h"

@implementation TabBarRouter

- (void)navigateToDismiss { 
    [self.viewController dismissViewControllerAnimated:true completion:nil];
}

- (void)navigateTo:(UIViewController *)vc {
    if([vc isKindOfClass:[UINavigationController class]]){
        [self.viewController presentViewController:vc animated:true completion:nil];
    } else if ([vc isKindOfClass:[UIViewController class]]) {
        if (self.viewController.navigationController){
            [self.viewController.navigationController pushViewController:vc animated:true];
        } else {
            [self.viewController presentViewController:vc animated:true completion:nil];
        }
    }
}

@end
