//
//  TabBarPresenter.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 21/04/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "TabBarProtocols.h"

@interface TabBarPresenter: NSObject<TabBarPresenterInterface>
@property (nonatomic, weak) NSObject<TabBarView> *view;
- (instancetype)initWithView:(NSObject<TabBarView>*)view
                      router:(NSObject<TabBarWireframeInterface>*)router;
@end


