//
//  VKAuthScreenRouter.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "VKAuthScreenRouter.h"
#import "VKAuthScreenProtocols.h"

@implementation VKAuthScreenRouter

- (void)navigateToDismiss { 
    [self.viewController dismissViewControllerAnimated:YES completion:nil];
}

- (void)navigateTo:(UIViewController *)vc {
    if([vc isKindOfClass:[UINavigationController class]]){
        [self.viewController presentViewController:vc animated:YES completion:nil];
    } else if ([vc isKindOfClass:[UIViewController class]]) {
        if (self.viewController.navigationController){
            [self.viewController.navigationController pushViewController:vc animated:YES];
        } else {
            [self.viewController presentViewController:vc animated:YES completion:nil];
        }
    }
}

@end
