//
//  VKAuthScreenPresenter.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 18/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "VKAuthScreenProtocols.h"

@interface VKAuthScreenPresenter: NSObject<VKAuthScreenPresenterInterface>
@property (nonatomic, weak) NSObject<VKAuthScreenView> *view;
- (instancetype)initWithView:(NSObject<VKAuthScreenView>*)view
                      router:(NSObject<VKAuthScreenWireframeInterface>*)router;
@end


