//
//  MainMenuProtocols.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 21/04/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import "MainMenuCell.h"

NS_ASSUME_NONNULL_BEGIN

//Router implement navigateTo func
@protocol MainMenuWireframeInterface <NSObject>

//example
@required - (void)navigateToDismiss;

@end

@protocol MainMenuView <NSObject>

- (void)displayMenuViewModels:(NSArray <MainMenuCellViewModel *>*)viewModels;

@end

@protocol MainMenuPresenterInterface <NSObject>

- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidAppear;
- (void)viewWillDissappear;
- (void)viewDidDissappear;

@end


NS_ASSUME_NONNULL_END
