//
//  MainMenuProtocols.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 21/04/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import "MainMenuCell.h"
#import "MainMenuHeader.h"
#import "MainMenuDataMediator.h"

NS_ASSUME_NONNULL_BEGIN

//Router implement navigateTo func
@protocol MainMenuWireframeInterface <NSObject>

//example
@required - (void)navigateToDismiss;
- (void)navigateToAuth;

@end

@protocol MainMenuView <NSObject>

- (void)displayMenu:(NSArray <MainMenuDataMediator *>*)viewModels;

@end

@protocol MainMenuPresenterInterface <NSObject>

- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidAppear;
- (void)viewWillDissappear;
- (void)viewDidDissappear;

- (void)didSelectRowAt:(NSIndexPath *)indexPath;

@end



NS_ASSUME_NONNULL_END
