//
//  MainMenuViewController.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 21/04/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "MainMenuViewController.h"
#import <UIKit/UIKit.h>
#import "UIView+Constraints.h"

@interface MainMenuViewController () <MainMenuView, UITableViewDelegate, UITableViewDataSource>

@property (nonatomic, strong) UITableView *tableView;
@property (nonatomic, strong) NSArray <MainMenuCellViewModel *>*dataSource;

@end

@implementation MainMenuViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    [self configureUI];
    [self.presenter viewDidLoad];
}

- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    [self.presenter viewWillAppear];
}

- (void)configureUI {
    [self configureTableView];
}

- (void)configureTableView
{
    self.tableView = [UITableView new];
    [self.view addSubview:self.tableView];
    [self.tableView fillSuperview];
    self.tableView.delegate = self;
    self.tableView.dataSource = self;
    [self.tableView registerClass:[MainMenuCell class] forCellReuseIdentifier:NSStringFromClass([MainMenuCell class])];
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    MainMenuCell *cell = [self.tableView dequeueReusableCellWithIdentifier:NSStringFromClass([MainMenuCell class])];
    if (indexPath.row < self.dataSource.count)
    {
        MainMenuCellViewModel *viewModel = self.dataSource[indexPath.row];
        [cell configureWithViewModel:viewModel];
    }
    return cell;
}

- (void)setDataSource:(NSArray<MainMenuCellViewModel *> *)dataSource
{
    _dataSource = dataSource;
    [self.tableView performBatchUpdates:^{
        [self.tableView reloadSections:[NSIndexSet indexSetWithIndex:0] withRowAnimation:UITableViewRowAnimationFade];
    } completion:nil];
}

- (void)displayMenuViewModels:(NSArray<MainMenuCellViewModel *> *)viewModels
{
    self.dataSource = viewModels;
}

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
{
    return UITableViewAutomaticDimension;
}

- (UIView *)tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section
{
    return [UIView new];
}

- (CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section
{
    return 0.01;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    if (self.dataSource == nil)
    {
        return 0;
    }
    return self.dataSource.count;
}

@end
