//
//  AddMealViewController.h
//  EatTrainSleepRepeat
//
//  Created pockerhead on 19/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <UIKit/UIKit.h>
#import "AddMealProtocols.h"

NS_ASSUME_NONNULL_BEGIN

@interface AddMealViewController : UIViewController<AddMealView>

@property (nonatomic, strong) NSObject<AddMealPresenterInterface>* presenter;

@end

NS_ASSUME_NONNULL_END
