//
//  AddMealViewController.m
//  EatTrainSleepRepeat
//
//  Created pockerhead on 19/05/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "AddMealViewController.h"
#import <UIKit/UIKit.h>
#import "UIView+Constraints.h"

@interface AddMealViewController () <AddMealView>

@property (strong, nonatomic) UITableView *tableView;

@end

@implementation AddMealViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    [self configureUI];
    [self.presenter viewDidLoad];
}

- (void)configureUI {
    UILabel *label = [UILabel new];
    [self.view addSubview:label];
    self.view.backgroundColor = UIColor.whiteColor;
    [label fillSuperview];
    label.text = @"ЗДЕСЬ ПОКА НИЧЕГО НЕТ ЕСЛИ НАЖАТЬ НАЗАД ТО В ВЫБРАННЫЙ ПРИЕМ ПИЩИ ДОБАВИТСЯ ГРУДКА";
    label.numberOfLines = 0;
    label.font = [UIFont systemFontOfSize:30];
//    UIBarButtonItem *dismissButton = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemStop target:self action:@selector(didSelectDismissButton)];
//    self.navigationItem.leftBarButtonItem = dismissButton;
}


- (void) didSelectDismissButton
{
    [self.presenter didSelectDismissButton];
}
@end
